description: //This file is the configuration file for the XCPC_board project
database:
  cfTable: cf
  nkTable: nk
  vjTable: vj
  lgTable: lg
  Message:
    name: XCPC_board_DB
    host: localhost:3306
    username: root
    password: 10086
