#//This file is the configuration file for the XCPC_board project
database:
  Mysql:
    name: XCPC_board_mysql
    host: localhost:3306
    username: root
    password: 10086
    #  cfTableName cf
    #  nkTableName nk
    #  vjTableName vj
    #  lgTableName lg
  Redis:
    host: localhost:6379
    password: 10086