description: //This file is the configuration file for the XCPC_board project
database:
  Msg:
    name: XCPC_board
    host: localhost:3306
    username: root
    password: 10086
  cfTable: cf
  nkTable: nk
  vjTable: vj
  lgTable: lg